from snakemake.utils import min_version
min_version("5.12.0")

report: "report/workflow.rst"
configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/install.smk"
include: "rules/remote.smk"
include: "rules/noise.smk"
include: "rules/sb9.smk"
include: "rules/bulk.smk"
include: "rules/sims.smk"

rule all:
    input:
        get_final_output()
