from snakemake.utils import min_version, validate
min_version("5.12.0")

configfile: "config/config.yaml"
validate(config, "schemas/config.schema.yaml")

container: "docker://ghcr.io/dfm/one-datum:main"

include: "rules/data.smk"
include: "rules/noise.smk"

rule check:
    output:
        "face.txt"
    conda:
        "envs/environment.yml"
    shell:
        "python -m pip freeze"

rule all:
    input:
        "resources/data/noise-model.fits",
        "resources/data/SB9public",
        "resources/data/kepler_dr2_1arcsec.fits",
        "resources/data/gold_sample.fits"
    log:
        "results/logs/all.log"
    shell:
        "ls"
